stages:
  - build
  - deploy

before_script:
  - docker-compose run web python manage.py migrate
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-django-app .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push my-django-app

deploy:
  stage: deploy
  image: docker/compose:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose up -d
