# Generated by Django 4.2.1 on 2023-05-11 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prefix', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(max_length=20, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('budget_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.budgetline')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_memos', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_memos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('staff_id', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('compassionate', 'Compassionate Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('other', 'Other')], max_length=20)),
                ('annual_leave_entitled', models.IntegerField()),
                ('leave_days_taken', models.IntegerField(default=0)),
                ('leave_days_requested', models.IntegerField()),
                ('remaining_leave_days', models.IntegerField(default=0)),
                ('proposed_leave_start_date', models.DateField(blank=True, null=True)),
                ('proposed_leave_end_date', models.DateField(blank=True, null=True)),
                ('handing_over_notes_done', models.BooleanField(default=False)),
                ('resumption_date', models.DateField(blank=True, null=True)),
                ('contact_details', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('is_declined', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('handing_over_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
