# Generated by Django 4.2.1 on 2023-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='purpose',
            field=models.TextField(default='', max_length=500),
        ),
    ]
